### ISSUE TITLE
Google Login implementation

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#10]
Start implementing the google login
1. Frontend - google login btn to get the token from the user
2. Backend - use the token to get user info and record it in db

API URL : 
- {server-path}/user/login

Backend branch:
- https://github.com/UF-CEN5035-2022SpringProject/GatorStore/tree/spr1-backend-feature/login

Frontend branch
- https://github.com/UF-CEN5035-2022SpringProject/GatorStore/tree/spr%7B1%7D-sfrontend-%7Bfeature%7D/%7Bgoogle-button%7D
- https://github.com/UF-CEN5035-2022SpringProject/GatorStore/tree/spr1-sfrontend-demo/googleapi

**Comment by yimingStar** [comment]
[Survey on Google login](https://github.com/UF-CEN5035-2022SpringProject/GatorStore/issues/7)

**Comment by chouhy** [comment]
OK. Now I got something to work.
I now can create a youtube livestream via code.
How it works:
1. program generate an oauth url
![image](https://user-images.githubusercontent.com/11768359/151686121-dcff7cb7-592f-403a-9e03-660bb5f40f70.png)
2. open the url
![image](https://user-images.githubusercontent.com/11768359/151686131-e76c01b0-695c-4a33-9abe-f08dd8ee4afd.png)
3. select a youtube live enabled account
4. google will send the code to the redirect url by something like this. (So @yimingStar you might need to provide an endpoint for receiving oauth response.)
http://localhost/testing.html?state=state& **code=4/0AX4XfWjBfbSRJR7KUo2KBlwwMq2hb5IyI9mGYQRcDWvrTGfZjMJH5G8qi0toSOXs_9GOgQ** &scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube#
5. (backend should receive the code) Do the handshake and get accesstoken.
6. configure livestream title and other stuff
7. insert it to youtube
![image](https://user-images.githubusercontent.com/11768359/151686332-2da70c8a-9911-4d43-b077-3d36ee7d393a.png)

**Comment by yimingStar** [comment]
@chouhy Great work!
Quick confirm about the process
1. So, after picking the email, the frontend will redirect to [http://localhost/testing.html](http://localhost/testing.html) with the **code** in params.
2. **Frontend** will call a backend API to pass the code (For example /user/login?code=XXXX).
3. **Backend** will receive the code and try to get the access token and get the user info (most important is the **email**) 
4. **Backend** response success to frontend if the access token and the user info have successfully verified by the backend.

**Comment by chouhy** [comment]
> @chouhy Great work! Quick confirm about the process
> 
> 1. So, after picking the email, the frontend will redirect to http://localhost/testing.html with the **code** in params.
> 2. **Frontend** will call a backend API to pass the code (For example /user/login?code=XXXX).
> 3. **Backend** will receive the code and try to get the access token and get the user info (most important is the **email**)
> 4. **Backend** response success to frontend if the access token and the user info have successfully verified by the backend.
yeah correct

**Comment by chouhy** [comment]
> 2. Frontend will call a backend API to pass the code (For example /user/login?code=XXXX).

@llerenabarruetos We need some frontend support here. Thanks.

**Comment by yimingStar** [comment]
@llerenabarruetos  Check this: https://www.npmjs.com/package/react-google-login
Thanks!

**Comment by llerenabarruetos** [comment]
Thank you the link @yimingStar.  
I made the '/testing' page to test this on the 'seller-frontend-test' branch (since main won't be updated with the react-router code until later) that gets the code number from the url (gets XXXX from localhost:3000/testing?code=XXXX) as requested here:
> 1. .... the frontend will redirect to http://localhost/testing.html with the code in params.
> 2. Frontend will call a backend API to pass the code (For example /user/login?code=XXXX).

I am unsure of the backend API call that this code will go into but I'm hoping we will resolve this at the meeting later today. This /testing page will be usable once we get the backend and frontend code in the same branch.

**Comment by llerenabarruetos** [comment]
1. User arrives on /landingpage
2. User clicks on "Google Sign In" button on header
	It has the following React Component:
	<GoogleLogin returnUrl={localhost:3000/testing}  ... other parameters />
3. User is taken to a google url that was generated via oauth
	a. user chooses their Google account with which they want to proceed
	b. user clicks continue and agrees to yield that info
4. Google takes the user back to the returnUrl set in the React component
5. Now, User has arrived at: localhost:3000/testing?code=3918&state=state&scope=stuff

6. **KEY:** Testing's JS file needs to send a POST message to the "backend URL" (Yiming specified) CONTAINING THE CODE parameter of the URL

7. The "Backend URL" receives code from POST and does handshake with this newly-logged-in user's info 
8. REMEMBER: POST message to "Backend URL" does not change the current webpage (/testing). 
	Backend needs to respond "SUCCESS" to front-end if the access token and user info are verified.
	I guess after that "SUCCESS", the JS file for /testing will display whatever a verified logged-in user should see
