### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#122]
Unit test frontend & backend

**Comment by yimingStar** [comment]
Postman Automation test Script
https://trailheadtechnology.com/basic-api-test-automation-with-postman-test-scripts-and-newman/

**Comment by chouhy** [comment]
Backend unit testing issue: #129

**Comment by llerenabarruetos** [comment]
Front-end testing suite expanded for the buyer project in [PR 135](https://github.com/UF-CEN5035-2022SpringProject/GatorStore/pull/135/)
