### ISSUE TITLE
Implementing Seller Frontend

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#13]
# Issue Description:
React being made mainly for single-page applications. We need to decide how we will equip our project with multi-page functionality; with each pages have a different URL.

**Comment by llerenabarruetos** [comment]
To implement the many pages GatorStore will need, we will use the **_React Router (react-router-dom) library._**

Version 6.2.1 was installed to the React project.

**Comment by yimingStar** [comment]
Merge the basic React App into [seller-frontend-test](https://github.com/UF-CEN5035-2022SpringProject/GatorStore/tree/seller-frontend-test)
https://github.com/UF-CEN5035-2022SpringProject/GatorStore/pull/26
