### ISSUE TITLE
Build backend server test

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#27]
Testing Command
Go to the src file and enter the command
```
sh autoTest.sh
```

1. Test the database operation function for each obj is correct
    - Go through all the query functions that the API level will use.
    
3. Test the Login, Live Streaming API is valid
     - Youtube API, we'll focusing on containing the correct credential key for calling the API
     - The token might be expired, but we still can guarantee our server is able to connect to Google API

**Comment by yimingStar** [comment]
https://pkg.go.dev/testing

Try to build testing branchmarks.
Using ```go test``` to check the result

**Comment by yimingStar** [comment]
Components 
- Login
   - get code
   - get access token
- Live
- DB (retrieving objects)
   - user obj
   - store obj
   - live obj

**Comment by yimingStar** [comment]
Simple Examples of Unit Testing: 
https://ieftimov.com/posts/testing-in-go-go-test/

HTTP Testing: 
https://pkg.go.dev/net/http/httptest

**Comment by chouhy** [comment]
# Testing for Login
We use Google login so it involves login code manually generated by Google authorization consent form.
As a result, it is not possible to test the whole login process with automated testing.
We use invalid login code to test if we can handle error.
# Testing for Live
Same as above, this time we need access token from Google which will expire very soon and cannot be obtained by automated testing.
Thus, we are testing if we can handle error response from Google and notify user.

**Comment by yimingStar** [comment]
# Testing for database unit
---
We create unit testing on a different objects in database
For example, user object we'll go through ADD, GET, UPDATE, DELETE operations
***each step we do checking to make sure the same function we use in the APIs is correct***
