### ISSUE TITLE
Research + Build Frontend Tests

### ISSUE THREAD

**Issue by llerenabarruetos** [UF-CEN5035-2022SpringProject/GatorStore#44]
Research and later implement method(s) to test the frontend interface (eg. via automated clicking programs, etc.) and whether or not it has successfully integrated the backend.

**Comment by llerenabarruetos** [comment]
Options:
- [Selenium WebDriver](https://www.selenium.dev) ([tutorial](https://www.testim.io/blog/how-much-does-selenium-cost/))
- [Cypress](https://www.cypress.io)
  - Recommended by Prof. Dobra for end-to-end testing and integration tests. 
  - Open Source 
- [WebDriverIO](https://webdriver.io)

**Comment by llerenabarruetos** [comment]
Cypress Testing for Logging In:
For this basic task, some approaches were taken:     

1.[ cypress-social-login (A library recommended by Cypress)](https://github.com/lirantal/cypress-social-logins)
Unfortunately, this library's functionality is cut short by either a Google 403 error, a Google error pertaining to cookies of a browser, and a Google error saying that the current browser is not secure - all of which happen before showing the field for the user's password in Google's authentication page. Cypress only interacts with elements from the origin of a test, in this case, that is localhost:3000. Going to the Google login page brings the test to a new origin, which is denied by Google's security measures.
While the library might have worked before, it currently is subject to tighter security measures from Google regarding the browser where the website is ran and testing program controlling it (from 2020).    

2.[ Programmatically Interacting with Google's API](https://docs.cypress.io/guides/testing-strategies/google-authentication#Google-Developer-Console-Setup)
This was one of the practices [recommended ](https://docs.cypress.io/guides/references/best-practices#Visiting-external-sites)by Cypress.
It involves sending a POST request to Google's login url. However, we discovered that manually inputting a password and an email combination is a required step before Google lets you use it to log in (and gives the user code we want to pass to our API to retrieve a user's JWToken, email, name, etc.). 

To solve this, [Selenium ](https://www.selenium.dev) testing might be implemented if Google's API is confirmed to not be able to be accessed with a POST request.

**Comment by chouhy** [comment]
related issue: #67
