### ISSUE TITLE
fetch() CORS/preflight issue

### ISSUE THREAD

**Issue by chouhy** [UF-CEN5035-2022SpringProject/GatorStore#58]
We will face CORS problem when fetch() headers include "Authorization".
[solution](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe)

**Comment by yimingStar** [comment]
What is a preflight request
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
