### ISSUE TITLE
Build stream status maintained by users

### ISSUE THREAD

**Issue by chouhy** [UF-CEN5035-2022SpringProject/GatorStore#59]
A stream status shown in the frontend and stored in the backend.

**Comment by chouhy** [comment]
Backend side implementation:
api [documentation](https://github.com/UF-CEN5035-2022SpringProject/GatorStore#sa2-store-livestream-status-api)
Use the jwtToken provided by client to query associate [store object](https://github.com/UF-CEN5035-2022SpringProject/GatorStore#store-object) from the database.
```
store object example
{
  'id': "GatorStore_1",
  'name': "GoGoGator",
  'userId': "11001",
  'createTime': "2006-01-02T15:04:05Z07:00",
  'updateTime': "2006-01-02T15:04:05Z07:00",
  'isLive': True
  'liveId': "132001"
}
```
Client can either PUT or GET to this API. PUT for updating isLive value. GET for getting current isLive value.

**Comment by llerenabarruetos** [comment]
![image](https://user-images.githubusercontent.com/40399062/156613707-a9c4b2a4-7640-475a-8e8c-f618163ccb71.png)      

![image](https://user-images.githubusercontent.com/40399062/156614156-5c725721-69e9-4677-8082-f5677e9ed061.png)     
Title is sent to backend along with user's authenticated information.      

      
   
![image](https://user-images.githubusercontent.com/40399062/156614704-9e7a1248-2be4-406b-96b7-6f63217b7b62.png)     

![image](https://user-images.githubusercontent.com/40399062/156615137-04a187ff-3018-4fff-bcfc-a9b5d2f0e631.png)
