### ISSUE TITLE
Build ErrorCode Responses

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#62]
Build a general response with HTTP status and with status code
- 0 status code will be success others will be error
- According to the [error code table](https://github.com/UF-CEN5035-2022SpringProject/GatorStore#global-errorcode),  the frontend has to execute different actions

For example, down below is the response without the correct JWT token for requesting user API
```
{
    "status": 1000,
    "result": {
        "msg": "Invalid JWT, not found"
    }
}
```
<img width="1004" alt="errorExample" src="https://user-images.githubusercontent.com/69064626/156217522-50b7cf62-6d02-4c88-b457-310cdfc82b86.png">

**Comment by yimingStar** [comment]
Using method on the Response function

**Comment by yimingStar** [comment]
@chouhy 
Error Response and Document in Livestream functions

**Comment by chouhy** [comment]
Error code mapping reference: [here](https://github.com/UF-CEN5035-2022SpringProject/GatorStore#global-errorcode)
Response format:
```
{
    "status": 800,
    "result": {
       "errorName": "MISS_PARAMS"
    }
}
```
