### ISSUE TITLE
Survey and design the Google Login

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#7]

**Comment by yimingStar** [comment]
@chouhy please post the website or material you surveyed in this issue for further discussion, thank you!

**Comment by chouhy** [comment]
https://developers.google.com/identity/protocols/oauth2
https://github.com/googleapis/google-api-go-client/blob/main/GettingStarted.md

**Comment by chouhy** [comment]
example code https://pkg.go.dev/golang.org/x/oauth2#example-Config

**Comment by chouhy** [comment]
https://developers.google.com/identity/protocols/oauth2/web-server?hl=en

**Comment by chouhy** [comment]
api library https://console.developers.google.com/apis/library
service account https://developers.google.com/identity/protocols/oauth2/service-account?hl=en

**Comment by chouhy** [comment]
youtube live streaming api https://developers.google.com/youtube/v3/live/getting-started
register app https://developers.google.com/youtube/registering_an_application

**Comment by chouhy** [comment]
sign in with google https://developers.google.com/identity/sign-in/web/sign-in

**Comment by chouhy** [comment]
sign in with google account BACKEND part https://qvault.io/golang/how-to-implement-sign-in-with-google-in-golang/

**Comment by chouhy** [comment]
what we do is like this
https://developers.google.com/oauthplayground/

**Comment by chouhy** [comment]
GO code example https://developers.google.com/youtube/v3/code_samples/go#authorize_a_request
