### ISSUE TITLE
Implement chat room (Buyer Side)

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#74]
# Can we implement the Ideal Order System?
Our original feature design is to build a chat room the user can create orders with comments during the live.
However, we finally decide to implement a Youtube chat room by iframe implementation. 
But then we have to drop this feature.

#### ***Reason: the Youtube chatroom identity will not be able to bind to our user system, even though we are all using Google login***

It's because we cannot retrieve the data from the iframe.

#### Work Around - we decide to implement Product Info Page and let user to buy product from ***Feature Items (live streamers can select a specific product list shows down below the live iframe)***

![LiveStreamStore](https://user-images.githubusercontent.com/69064626/161338990-129754dd-325d-4696-8cd0-9d7cf1c7a734.jpeg)

**Comment by chouhy** [comment]
[Reference](https://support.google.com/youtube/answer/2524549?hl=en)
Basic idea is that we need livestream id and create the iframe with that id.
Luckily from [SA1. Store Livestream API](https://github.com/UF-CEN5035-2022SpringProject/GatorStore#sa1-store-livestream-api) we already got the livestream id as the response.

**Comment by chouhy** [comment]
<iframe width="425" height="344" src="https://www.youtube.com/embed/K_79tKI4II8?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by yimingStar** [comment]
The implementation is in this commit 
https://github.com/UF-CEN5035-2022SpringProject/GatorStore/commit/2acf0975630b05c27aa944677a50d67ec5f809e2
