### ISSUE TITLE
Build a simple buyer webpage

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#75]
Buyer Pages 
- Landing (Maybe)
- Store page (link create seller)
   - Chat room
   - Product list
   - Stream Iframe

**Comment by llerenabarruetos** [comment]
The new branch that contains this new buyer React App is: s**pr3-bfrontend-navigation/pages**     

To run the app, proceed to that branch and go to: **GatorStore/buyer-frontend/gatorstore-buyer** (name of the React App).     

It currently has a landing page (routed to "/") and a store page ("/store"), which is equipped with the "not-live" and "live" front-end states. The next step is to pull the live status, possibly chat (maybe?), and the iframe embed string from an API. It currently has a test lofi stream iframe and the state can be changed manually with SetLiveInfoBarState("not-live" or "live").

**Comment by yimingStar** [comment]
The application is create in this comment
https://github.com/UF-CEN5035-2022SpringProject/GatorStore/commit/ff5ebf51eba3a0415e677baf2280bda70e04cc10
