### ISSUE TITLE
Create and Update Store, Create and Update Product API, Order API

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#76]
New APIs

# Users
- UA2 Get User Info [v]
- UA3 User Store list [v]
- UA4 User Order list  [v]

# Stores
- SA0 Create Store [v]
- SA1 Get Store [v] - REPLACED BY #83 
- SA2 Store product list [v]
- SA3 Store order list [v]
- SA4 Store live list 
  - SA4-1 Store live Orders 
- SA5 Store Recommend list

# Product
- PA1 Product Create [v]
- PA2 Product Get [v]
- PA3 Product Update [v]
- PA4 Product Purchase (Order Create) [v]
- PA5 Product Delete [v]

# Order System
- Order Object [v]
- Email to the user?

----
3/29
Backend 
- Order System PA4 (Jim)
- OrderList shows UA4, SA3, SA4 (YiMing)

Frontend
- UA3, UA4 (Sebastian)
- Product APIs (Sebastian)
- Image Upload (YiMing)

**Comment by yimingStar** [comment]
# SA4. Store Product List API
---
#### SA4. Store Product List API
Get the products according to the store, split the item with page
 - Method: GET
 - {routePath}: /store/{store id}/productList?page={page}
   - page parameter decide which page requesting, if overflow, return the last page. If missing, return page 0.
 
 - **Header**
   | Name | Type | Description |
   | --- | --- | --- |
   | Authorization | string | Use for GatorStore Login |
   
- **Request Body Table**   
    Empty request body
    GET Example:
    ```
    {
    }
    ```
- **Response**  
    Success: 
    ```
    {
      'storeId': "GatorStore_1",
      'name': "GoGoGator",
      'totalPage': 15,
      'currentPage': 0,
      'productList': [
        {productObject},
        {productObject},
        ...
      ]
    }
    ```

    Error:
     ```
     {
         "status": 1000,
         "result": {
            "errorName": "MissingJwtTokenCode"
         }
     }
     ```
   
     Error Code Table for error situation:

      | ErrorName | ErrorCode | HttpStatus | Description |
      | ---  | --- | --- | --- |
      | MissingJwtTokenCode | 1000 | 401 | |
      | InvalidJwtTokenCode | 1001 | 401 | Expire or invalid jwtToken |

**Comment by yimingStar** [comment]
# SA5. Store OrderList API
---
Get the orders according to the store, split the item with page
 - Method: GET
 - {routePath}: /store/{storeId}/orderList?page={page}
   - page parameter decide which page requesting, if overflow, return the last page. If missing, return page 0.
 
 - **Header**
   | Name | Type | Description |
   | --- | --- | --- |
   | Authorization | string | Use for GatorStore Login |
   
- **Request Body Table**   
    Empty request body
    GET Example:
    ```
    {
    }
    ```
- **Response**  
    Success: 
    ```
    {
      'storeId': "GatorStore_1",
      'totalPage': 15,
      'currentPage': 0,
      'orderList': [
        {orderObject},
        {orderObject},
        ...
      ]
    }
    ```

    Error:
     ```
     {
         "status": 1000,
         "result": {
            "errorName": "MissingJwtTokenCode"
         }
     }
     ```
   
     Error Code Table for error situation:
      | ErrorName | ErrorCode | HttpStatus | Description |
      | ---  | --- | --- | --- |
      | MissingJwtTokenCode | 1000 | 401 | |
      | InvalidJwtTokenCode | 1001 | 401 | Expire or invalid jwtToken |

**Comment by chouhy** [comment]
Product Object
   | Name | Type | Description |
   | ---  | --- | --- |
   | name | string | product name |
   | price | string | product price |
   | description | string | product introduction |
   | quantity | string | how many product in stock |
   | picture | string | picture in base64 |
   | storeId | string | publish to which store |
   | createTime | string | createTime |
   | updateTime | string | updateTime|

**Comment by chouhy** [comment]
#### PA3. Product Update API
 - Method: POST
 - {routePath}: /product/{product id}
 - **Header**
   | Name | Type | Description |
   | --- | --- | --- |
   | Authorization | string |  jwtToken |
   
 - **Request Body Table**
   | Name | Type | Description |
   | ---  | --- | --- |
   | (optional)name | string | product name |
   | (optional)price | string | product price |
   | (optional)description | string | product introduction |
   |(optional) quantity | string | how many product in stock |
   | (optional)picture | string | picture in base64 |

    Example:
     ```
     {
         'name': 'gator',
         'price": '1000',
         'description':'real gator',
         'quantity': '1',
         'picture':'123123123'
     }
     
 - **Response**  
    Success: 
    ```
    {
        "status": 0,
        "result": {
              {productObject}
        }
    }
    ```

    Error:
     ```
     {
         "status": 800,
         "result": {
            "errorName": "MISS_PARAMS"
         }
     }
     ```
   
     Error Code Table for error situation:

      | ErrorName | ErrorCode | HttpStatus | Description |
      | ---  | --- | --- | --- |
      | MISS_PARAMS | 800 | 400 | |
      | INVALID_PARAMS | 801 | 400 | |
      | NO_JWTTOKEN | 1000 | 401 | Missing JwtToken |
      | INVALID_JWTTOKEN | 1001 | 401 | Expire or invalid jwtToken |
      | INVALID_ACCESSTOKEN | 9000 | 403 | Expire Google Access Token |
  
---

**Comment by chouhy** [comment]
#### PA3. Product Purchase API
 - Method: POST
 - {routePath}: /product/{product id}
 - **Header**
   | Name | Type | Description |
   | --- | --- | --- |
   | Authorization | string |  jwtToken |
   
 - **Request Body Table**
   | Name | Type | Description |
   | ---  | --- | --- |
   |id | string | product id |
   |quantity | string | how many product in stock |

    Example:
     ```
     {
         'id': '11001',
         'quantity': '1'
     }
     
 - **Response**  
    Success: 
    ```
    {
        "status": 0,
        "result": {
              'name': 'gator',
              'id':'11001',
              'subtotal": '1000',
              'quantity': '1',
        }
    }
    ```

    Error:
     ```
     {
         "status": 800,
         "result": {
            "errorName": "MISS_PARAMS"
         }
     }
     ```
   
     Error Code Table for error situation:

      | ErrorName | ErrorCode | HttpStatus | Description |
      | ---  | --- | --- | --- |
      | MISS_PARAMS | 800 | 400 | |
      | INVALID_PARAMS | 801 | 400 | |
      | NO_JWTTOKEN | 1000 | 401 | Missing JwtToken |
      | INVALID_JWTTOKEN | 1001 | 401 | Expire or invalid jwtToken |
      | INVALID_ACCESSTOKEN | 9000 | 403 | Expire Google Access Token |
  
---

**Comment by chouhy** [comment]
#### PA3. Product Delete API
 - Method: DELETE
 - {routePath}: /product/{product id}
 - **Header**
   | Name | Type | Description |
   | --- | --- | --- |
   | Authorization | string |  jwtToken |
   
 - **Request Body Table**
   | Name | Type | Description |
   | ---  | --- | --- |

    Example:
     ```
     {
     }
     
 - **Response**  
    Success: 
    ```
    {
        "status": 0,
        "result": {
        }
    }
    ```

    Error:
     ```
     {
         "status": 800,
         "result": {
            "errorName": "MISS_PARAMS"
         }
     }
     ```
   
     Error Code Table for error situation:

      | ErrorName | ErrorCode | HttpStatus | Description |
      | ---  | --- | --- | --- |
      | MISS_PARAMS | 800 | 400 | |
      | INVALID_PARAMS | 801 | 400 | |
      | NO_JWTTOKEN | 1000 | 401 | Missing JwtToken |
      | INVALID_JWTTOKEN | 1001 | 401 | Expire or invalid jwtToken |
      | INVALID_ACCESSTOKEN | 9000 | 403 | Expire Google Access Token |
  
---

**Comment by yimingStar** [comment]
# Order Object
--- 
Each Order will have unique and belong to one user who purchases the object.

The key will be **orderId**, and the value will be as below:
| Var/Method | Key/Optional | Type | Description |
| ---  | --- | --- | --- |
| id | K | string | orderId- unique identifier |
| userId | | string | unique buyerId|
| createTime |  | string | create datetime | 
| productId | | string | products ID |
| liveId | | string | liveObj's ID, if buyers click from the live product list, else it will be an empty string |
| subTotal | | float64 | total payment |
| quantity | | int | | 

JSON Example:
```
{
   "id": orderId
   "productId": purchase product
   "createTime": ""
   "liveId": "weqwe" (empty if false)
   "subTotal": 4000
   "quantity": 10,
   "userId": buyerId
}
```
---

**Comment by yimingStar** [comment]
# SA5. Store Recommend List API
---
Get the products according to the store, split the item with page
 - Method: GET
 - {routePath}: /store/recommend-list?page={page}
   - page parameter decide which page requesting, if overflow, return the last page. If missing, return page 0.
 
 - **Header** - empty
   
- **Request Body Table**   
    Empty request body
    GET Example:
    ```
    {
    }
    ```
- **Response**  
    If storeList is empty, the value will be null
    Success: 
    ```
    {
      'maxPage': 3, (start at 0)
      'currentPage': 0,
      'storeList': [
        {storeObj},
        {storeObj},
        ...
      ]
    }
    ```

    Error:
     ```
     {
         "status": 1000,
         "result": {
            "errorName": "MissingJwtTokenCode"
         }
     }
     ```
   
     Error Code Table for error situation:

      | ErrorName | ErrorCode | HttpStatus | Description |
      | ---  | --- | --- | --- |
      | MissingJwtTokenCode | 1000 | 401 | |
      | InvalidJwtTokenCode | 1001 | 401 | Expire or invalid jwtToken |
